[package]
name = "quantx-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
scraper = "0.18"
tokio = { version = "1", features = ["full"] }
yahoo_finance_api = "4.1.0"
